fix minor errors

diff --git a/post_install b/post_install
--- a/post_install
+++ b/post_install
@@ -20,13 +20,6 @@ EOF
   exit 1
 }
 
-add_sudoers_rule() {
-  local sudoers_tmp=$(mktemp)
-  echo "kayd ALL=(ALL) NOPASSWD: /usr/bin/pacman, /usr/bin/git, /usr/bin/xdg-mime, /usr/bin/paru, /usr/bin/makepkg" > "$sudoers_tmp"
-  visudo -cf "$sudoers_tmp" && cat "$sudoers_tmp" >> /etc/sudoers.d/kayd_nopasswd
-  rm -f "$sudoers_tmp"
-}
-
 install_pacman_packages() {
   local packages=(
     ttf-font-awesome tmux dmenu xclip noto-fonts-emoji mpv yt-dlp ttf-cascadia-code gdb
@@ -152,8 +145,27 @@ keyboard_backlight() {
   sed -i 's/PRODUCT = 0xC965/PRODUCT = 0xC975/' l5p-kbl/l5p_kbl.py
 }
 
+add_sudoers_rule() {
+  local sudoers_tmp=$(mktemp)
+  echo "kayd ALL=(ALL) NOPASSWD: /usr/bin/pacman, /usr/bin/git, /usr/bin/xdg-mime, /usr/bin/paru, /usr/bin/makepkg" > "$sudoers_tmp"
+  visudo -cf "$sudoers_tmp" && cat "$sudoers_tmp" >> /etc/sudoers.d/kayd_nopasswd
+  rm -f "$sudoers_tmp"
+}
+
+configure_check_network() {
+  local ssid=$(cat /home/kayd/wifi_ssid)
+  local wifi_password=$(cat /home/kayd/wifi_password)
+
+  nmcli device wifi connect "$ssid" password "$wifi_password"
+  if ! nmcli -t -f active,ssid dev wifi | grep '^yes:' || ! ping -c 1 google.com &> /dev/null; then
+    echo "Network connection failed. Please check your settings."
+    exit 1
+  fi
+}
+
 run_all_options() {
   add_sudoers_rule
+  configure_check_network
   install_pacman_packages
   install_paru_packages
   install_suckless_software
